name: gardeyn benches

on:
  workflow_dispatch:
    inputs:
      n_runs:
        description: 'Number of times to run each instance'
        default: 16
        required: true
        type: number
      run_time_s:
        description: 'Time per run in seconds'
        default: 1200
        required: true
        type: number
      cpu_tag:
        description: 'CPU type for runner (5950X, 7950X)'
        required: true
        type: choice
        options:
          - 5950X
          - 7950X
          - 9950X

jobs:
  gardeyn0:
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: gardeyn0
      n_runs: ${{ fromJSON(inputs.n_runs) }}
      run_time_s: ${{ fromJSON(inputs.run_time_s) }}
      cpu_tag: ${{ inputs.cpu_tag }}
  gardeyn1:
    needs: gardeyn0
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: gardeyn1
      n_runs: ${{ fromJSON(inputs.n_runs) }}
      run_time_s: ${{ fromJSON(inputs.run_time_s) }}
      cpu_tag: ${{ inputs.cpu_tag }}
  gardeyn2:
    needs: gardeyn1
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: gardeyn2
      n_runs: ${{ fromJSON(inputs.n_runs) }}
      run_time_s: ${{ fromJSON(inputs.run_time_s) }}
      cpu_tag: ${{ inputs.cpu_tag }}
  gardeyn3:
    needs: gardeyn2
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: gardeyn3
      n_runs: ${{ fromJSON(inputs.n_runs) }}
      run_time_s: ${{ fromJSON(inputs.run_time_s) }}
      cpu_tag: ${{ inputs.cpu_tag }}
  gardeyn4:
    needs: gardeyn3
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: gardeyn4
      n_runs: ${{ fromJSON(inputs.n_runs) }}
      run_time_s: ${{ fromJSON(inputs.run_time_s) }}
      cpu_tag: ${{ inputs.cpu_tag }}
  gardeyn5:
    needs: gardeyn4
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: gardeyn5
      n_runs: ${{ fromJSON(inputs.n_runs) }}
      run_time_s: ${{ fromJSON(inputs.run_time_s) }}
      cpu_tag: ${{ inputs.cpu_tag }}
  gardeyn6:
    needs: gardeyn5
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: gardeyn6
      n_runs: ${{ fromJSON(inputs.n_runs) }}
      run_time_s: ${{ fromJSON(inputs.run_time_s) }}
      cpu_tag: ${{ inputs.cpu_tag }}
  gardeyn7:
    needs: gardeyn6
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: gardeyn7
      n_runs: ${{ fromJSON(inputs.n_runs) }}
      run_time_s: ${{ fromJSON(inputs.run_time_s) }}
      cpu_tag: ${{ inputs.cpu_tag }}
  gardeyn8:
    needs: gardeyn7
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: gardeyn8
      n_runs: ${{ fromJSON(inputs.n_runs) }}
      run_time_s: ${{ fromJSON(inputs.run_time_s) }}
      cpu_tag: ${{ inputs.cpu_tag }}
  gardeyn9:
    needs: gardeyn8
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: gardeyn9
      n_runs: ${{ fromJSON(inputs.n_runs) }}
      run_time_s: ${{ fromJSON(inputs.run_time_s) }}
      cpu_tag: ${{ inputs.cpu_tag }}